export const steps = [
  {
    stars: "★",
    title: "FILLING UP THE FORM",
    text: `HEAD TO THE REGISTER BUTTON ON THE EVENTS PAGE TO GET REDIRECTED TO UNSTOP. ONCE THERE, FILL IN ALL REQUIRED DETAILS WITH ACCURATE INFORMATION BEFORE THE REGISTRATION DEADLINE.
MISSION ISN'T COMPLETE UNTIL THE REQUIRED REGISTRATION FEE IS SUCCESSFULLY PAID. MAKE SURE EVERYTHING’S LOCKED IN BEFORE TIME RUNS OUT..`
  },
  {
    stars: "★★",
    title: "VERIFYING DETAILS",
    text: `OU TEAM WILL CONDUCT A THOROUGH VERIFICATION OF THE INFORMATION PROVIDED BY YOU. IF WE ENCOUNTER ANY ISSUES DURING THE VERIFICATION PROCESS, WE WILL CONTACT THE RELEVANT TEAM FOR RESOLUTION. IF EVERYTHING IS IN ORDER, YOU CAN EXPECT TO RECEIVE A CONFIRMATION EMAIL WITHIN 1-2 DAYS.`
  },
  {
    stars: "★★★",
    title: "ENTER THE COSMOS ",
    text: `ONCE THE CONFIRMATION EMAIL HITS YOUR INBOX, IT'S TIME TO ROLL OUT.
GEAR UP TO DOMINATE THE BATTLEFIELD IN FEBRUARY 2026 WHERE SPARKS IGNITE, STRATEGIES SHIFT, AND ONLY THE WORTHY RISE TO CLAIM VICTORY.`
  }
];
